Created Response Schema and added Status Code constants
ZeStream/zestream-server pull request #28
Opened 2023-01-01 17:03 UTC by loyaltytrooper

[feat] added statusCodes.go in constants and functions to create ErrorSchema

2023-01-01 17:04 UTC, loyaltytrooper commented
@abhishekraj272 @uzaxirr created a fresh PR that one got way messy

2023-01-01 17:40 UTC, uzaxirr requested changes

2023-01-01 17:40 UTC, uzaxirr commented on constants/status_codes.go
> +	226: "IMUsed",
This map should be added in `constants/constants.go` i don't think there's need to create a new file.
and i doubt if we gonna use soo many values so just limit it to the below mentioned one
```go
const HTTPStatusCodes := map[int]string{
	http.StatusOK:                   http.StatusText(http.StatusOK),
	http.StatusCreated:              http.StatusText(http.StatusCreated),
	http.StatusAccepted:             http.StatusText(http.StatusAccepted),
	http.StatusNonAuthoritativeInfo: http.StatusText(http.StatusNonAuthoritativeInfo),
	http.StatusNoContent:            http.StatusText(http.StatusNoContent),
	http.StatusBadRequest:           http.StatusText(http.StatusBadRequest),
	http.StatusUnauthorized:         http.StatusText(http.StatusUnauthorized),
	http.StatusForbidden:            http.StatusText(http.StatusForbidden),
	http.StatusNotFound:             http.StatusText(http.StatusNotFound),
	http.StatusMethodNotAllowed:     http.StatusText(http.StatusMethodNotAllowed),
	http.StatusConflict:             http.StatusText(http.StatusConflict),
	http.StatusInternalServerError:  http.StatusText(http.StatusInternalServerError),
}
```

2023-01-01 17:40 UTC, uzaxirr commented on helpers/response_schema.go
> +package helpers
this can be added in the `utils` directory itself

2023-01-01 18:35 UTC, uzaxirr requested changes
Create a new directory and file `types/types.go` this file will contain the struct which can be used for both Error and Sucess Response

`types/types.go`

```go
type Response struct {
	Status  int         `json:"status"`
	Data    interface{} `json:"data"`
	Error   interface{} `json:"error"`
}

```

and then you can modify the controller, an example of what the Ping controller may look like is

```go
func Ping(c *gin.Context) {
	response := Response{
		Status: HTTPStatusCodes[http.StatusOK],
		Data:   "pong",
		Error:  struct{}{},
	}
	c.JSON(http.StatusOK, response)
}
```

It may give the below output
```json
{
    "status": 200,
    "data": "pong",
    "error": {}
}
```

And for the `/generate-presigned-url`
```go
response := Response{
	Status: HTTPStatusCodes[http.StatusOK],
	Data: map[string]interface{}{
		"preSignedURL": "https://somebucket-bucket.s3.amazonaws.com/abcdefg",
		"videoID":      "109934677.mp4",
	},
	Error: struct{}{},
}
```

and in case of error the `Data` feild will be empty while the `Error` field will have the appropriate info

2023-01-05 07:15 UTC, uzaxirr commented
Hey @loyaltytrooper 
Working on this?

2023-01-07 19:55 UTC, uzaxirr commented
Closing this due to inactivity

2023-01-07 19:55 UTC, closed without merging