Fixed fatal logs
ZeStream/zestream-server pull request #44
Opened 2023-01-03 16:19 UTC by Missing-Parallax

2023-01-03 16:40 UTC, uzaxirr requested changes

2023-01-03 16:40 UTC, uzaxirr commented on utils/kafka.go
> +		log.Println("failed to dial leader:", err)
I would recommend to use `log.Error()` here

@abhishekraj272 Do we want to terminate this function in case error arises here?

2023-01-03 17:27 UTC, abhishekraj272 commented on utils/kafka.go
> +		log.Println("failed to dial leader:", err)
yeah, returning error would be better approach

2023-01-03 17:31 UTC, abhishekraj272 commented on utils/kafka.go
> +		log.Println("failed to dial leader:", err)
@uzaxirr you mean return err? there is no function as log.Error

2023-01-03 17:45 UTC, uzaxirr commented on utils/kafka.go
> +		log.Println("failed to dial leader:", err)
> @uzaxirr you mean return err? there is no function as log.Error


Any Error Level log is fine here, and then return an error from the function

2023-01-03 17:50 UTC, uzaxirr commented on utils/kafka.go
> +		log.Println("failed to dial leader:", err)
@abhishekraj272 
Do we also need to do error handling [here](https://github.com/ZeStream/zestream-server/blob/dev/controllers/kafka.go#L33) if this function returns an error, Ideally this Publish function should return a `message` and an `error`, and in the controller we should have checks for this error.

What do you think?

2023-01-03 17:52 UTC, abhishekraj272 commented on utils/kafka.go
> +		log.Println("failed to dial leader:", err)
this function should return the error and the response should be sent from the controller

2023-01-03 17:54 UTC, uzaxirr commented on utils/kafka.go
> +		log.Println("failed to dial leader:", err)
@Missing-Parallax 
Do you wish to incorporate these changes in this PR itself or should i create a new issue for it?

2023-01-06 11:06 UTC, uzaxirr commented
Hey @Missing-Parallax 
Any updates?

2023-01-06 11:25 UTC, Missing-Parallax commented
> Hey @Missing-Parallax Any updates?

Sorry, I am having exam tomorrow, so I did not check.
Will check after the exam, if thts not an issue

2023-01-06 20:49 UTC, uzaxirr commented
> > Hey @Missing-Parallax Any updates?
> 
> Sorry, I am having exam tomorrow, so I did not check. Will check after the exam, if thts not an issue

Not a problem at all

2023-01-07 17:36 UTC, uzaxirr commented
Closing this wrt #56

2023-01-07 17:36 UTC, closed without merging