Add timeouts for server
ZeStream/zestream-server pull request #46
Opened 2023-01-03 17:13 UTC by vivek378521

2023-01-03 17:15 UTC, vivek378521 commented
Here is the test SS
![Selection_016](https://user-images.githubusercontent.com/29369111/210407181-7db23448-b1f9-4085-86aa-990c19831335.png)

2023-01-03 17:23 UTC, uzaxirr requested changes

2023-01-03 17:23 UTC, uzaxirr commented on constants/constants.go
> +const WRITE_TIMEOUT = 1 * time.Second
Set it to 5 Sec
i.e
```go
const READ_TIMEOUT = 5 * time.Second
const WRITE_TIMEOUT = 5 * time.Second
```

2023-01-04 15:27 UTC, vivek378521 commented on constants/constants.go
> +const WRITE_TIMEOUT = 1 * time.Second
Done.

2023-01-05 07:27 UTC, uzaxirr approved these changes
LGTM, Thank you for your contribution!

2023-01-05 07:28 UTC, merged

2023-01-08 13:41 UTC, abhishekraj272 commented
we moved from gin to http server? @uzaxirr @vivek378521

2023-01-08 14:21 UTC, uzaxirr commented
> LGTM, Thank you for your contribution!

What no, the microservice is still a Gin server.

2023-01-08 14:45 UTC, abhishekraj272 commented
we are doing http.ServeAndListen() and gin.Run() both